---
id: Icalendar
name: Icalendar
full: iCalendar and vCard library
description: A library for dealing with iCalendar and vCard data.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Icalendar
authors:
  -
    name: Jan Schneider
    user: jan
    email: jan@horde.org
    active: true
    role: lead
  -
    name: Michael J Rubinsky
    user: mrubinsk
    email: mrubinsk@horde.org
    active: true
    role: developer
  -
    name: Chuck Hagenbuch
    user: chuck
    email: chuck@horde.org
    active: false
    role: lead
version:
  release: 3.0.0alpha5
  api: 3.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: LGPL-2.1-only
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^7.4 || ^8
    composer:
      horde/date: ^3
      horde/exception: ^3
      horde/mail: ^3
      horde/support: ^3
      horde/translation: ^3
      horde/util: ^3
  optional:
    composer:
      horde/test: ^3
